sonar.projectKey=onetoalfonso-del_komands-qa
sonar.organization=onetoalfonso-del

sonar.projectName=Komands QA
sonar.projectVersion=1.0

# Código fuente a analizar
sonar.sources=komands
sonar.tests=tests

# Cobertura generada por pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
